### ISSUE TITLE
Does baxter_simulator supports higher gazebo versions such as gazebo7?

### ISSUE THREAD

**Issue by SJTUzhanglj** [RethinkRobotics/baxter_simulator#93]
Currently is installed ros with ros-indigo-desktop-full, and the default version is gazebo 2.2.3 which is deprecated. i found gazebo7 have more useful tools and convenient for research. will this simulator supports gazebo7?

**Comment by IanTheEngineer** [comment]
ROS Indigo installs with gazebo 2.2.3, as can be found here: http://gazebosim.org/#status and ROS Indigo is EOL April 2019: http://wiki.ros.org/Distributions

As baxter_simulator currently only support ROS Indigo, and due to our development team size, this will be the only version of Gazebo we actively support, unless Gazebo 7 support comes as a community contribution.
